### ISSUE TITLE
What about web app code that isn’t installed via npm?

### ISSUE THREAD

**Issue by rauschma** [iarna/assetize#1]
How would such code be handled? Thanks!

AFAICT, you’d have to do the following inside such code:

```js
import demo from './assets/@iarna/demo-esm-2.js';
```

If that (local) code were to be included during asset installation, one could do:

```js
import demo from '@iarna/demo-esm-2'
```

**Comment by iarna** [comment]
As this is a just a WIP and I don't intend to do any further work with it _here_, (please see https://github.com/npm/npm/tree/npm-asset for the real version), I'm gonna close this.

Local loading would do the former, yes. There are a number of proposals underway in various standards groups to allow for cleaner handling of bare imports, this is a stop gap until they happen.
