### ISSUE TITLE
Bin script needs a shebang

### ISSUE THREAD

**Issue by evanplaice** [iarna/assetize#2]
### Environment

- Platform: ElementaryOS (Debian variant)
- Node -v: v8.9.4
- NPM -v: 5.6.0

### Steps to reproduce

1. Installed assetize via npm

```sh
npm install -g github:iarna/assetize
```

2. Install a package via assetize

```sh
assetize jquery-csv
```

### Unexpected Result

Doing this throws the following error

```sh
/home/evan/.nvm/versions/node/v8.9.4/bin/assetize: line 1: use strict: command not found
/home/evan/.nvm/versions/node/v8.9.4/bin/assetize: line 2: syntax error near unexpected token `('
/home/evan/.nvm/versions/node/v8.9.4/bin/assetize: line 2: `const system = require('@perl/system')'
```

### Fix

The bin script needs a shebang so the CLI knows to interpret it with NodeJS.

**Comment by iarna** [comment]
As this is a just a WIP and I don't intend to do any further work with it _here_, (please see https://github.com/npm/npm/tree/npm-asset for the real version), I'm gonna close this.
